queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label=ci:ready_to_merge
    merge_conditions:
      - base=main
      - label=ci:ready_to_merge
    checks_timeout: 2 h
    branch_protection_injection_mode: queue
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body_raw  }}
    merge_method: squash

pull_request_rules:
  - name: remove ci:ready_to_merge label
    conditions:
      - merged
    actions:
      label:
        remove:
          - ci:ready_to_merge
  - name: push to default merge queue
    conditions: []
    actions:
      queue:
